### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by mtauberjr** [Ozencb/yts-scraper#12]
Thank you for adding IMBD. However, I keep getting this error. 

Downloaded The Acid House (1998) 1080P                                          
Downloading:   0%|                      | 47/18974 [00:48<5:43:06,  1.09s/Files]Traceback (most recent call last):
  File "build/bdist.macosx-10.15-x86_64/egg/yts_scraper/main.py", line 153, in main
    scraper.download()
  File "build/bdist.macosx-10.15-x86_64/egg/yts_scraper/scraper.py", line 359, in download
    self.__initialize_download()
  File "build/bdist.macosx-10.15-x86_64/egg/yts_scraper/scraper.py", line 202, in __initialize_download
    self.__filter_torrents(movie)
  File "build/bdist.macosx-10.15-x86_64/egg/yts_scraper/scraper.py", line 255, in __filter_torrents
    self.__log_csv(movie_id, imdb_id, movie_name_short, year, language, movie_rating, quality, yts_url, torrent_url)
  File "build/bdist.macosx-10.15-x86_64/egg/yts_scraper/scraper.py", line 337, in __log_csv
    'Torrent URL': torrent_url
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 2: ordinal not in range(128)

**Comment by mtauberjr** [comment]
Had to use Python3.
